feature:repo-add mvn:org.fcrepo.camel/toolbox-features/4.5.2/xml/features
#feature:repo-add mvn:org.fcrepo.camel/toolbox-features/LATEST/xml/features
feature:install fcrepo-indexing-triplestore
feature:install fcrepo-indexing-solr
#feature:install fcrepo-reindexing
#feature:install fcrepo-fixity
#feature:install fcrepo-serialization
#feature:install fcrepo-audit-triplestore
# ab 4.5.3 feature:install fcrepo-service-activemq
